# Generated by Django 5.2.1 on 2025-10-20 12:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('annual_leave_days', models.IntegerField(default=30)),
                ('leave_days_taken', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('supervisor_comment', models.TextField(blank=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Supervisor Approval'), ('Supervisor Approved', 'Approved by Supervisor'), ('Supervisor Rejected', 'Rejected by Supervisor'), ('HR Approved', 'Approved by HR'), ('HR Rejected', 'Rejected by HR')], default='Pending', max_length=30)),
                ('date_requested', models.DateField(default=datetime.date.today)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.employee')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.supervisor')),
            ],
        ),
    ]
