# Generated by Django 5.2.1 on 2025-10-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_reset_year',
            field=models.IntegerField(default=2025),
        ),
    ]
